In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
#array of ones with 2 rows and 5 columns
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
####creating an array with 2 rows and 10 columns
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
#dividing range in equal parts
np.linspace(0,1,4)
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [17]:
#creates identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(3,2)

array([[0.84318152, 0.67321789],
       [0.78782602, 0.66321183],
       [0.09286655, 0.82506211]])

In [20]:
np.random.randint(3,10)

3

In [21]:
np.random.randint(5,20,5)

array([17,  9,  9, 16, 11])

In [23]:
sarray = np.arange(30)
sarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
#we can only reshape when elements of array = total elements of the new matrix
tarray = sarray.reshape(5,6)
tarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
sarray.min()

0

In [28]:
sarray.argmin()

0

In [29]:
sarray.max()

29

In [30]:
sarray.argmax()

29

In [34]:
#to have transpose of a matrix
tarray.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [35]:
tarray[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
arr[1:3]=100
arr

array([  1, 100, 100])

In [38]:
#2 DIMENSIONAL ARRAY
sample_matrix = np.array(([2,5,4,3],[24,53,12,54],[65,22,10,8]))
sample_matrix

array([[ 2,  5,  4,  3],
       [24, 53, 12, 54],
       [65, 22, 10,  8]])

In [39]:
sample_matrix[2][1]

22

In [40]:
sample_matrix[2:]

array([[65, 22, 10,  8]])

In [41]:
#here an array with 3 rows and 2 columns will be formed and it'll have its elements from all lists with there 
#3rd index one its first and 2nd index one as its second
sample_matrix[:,(3,2)]

array([[ 3,  4],
       [54, 12],
       [ 8, 10]])

In [ ]:
#SELECTION TECHNIQUES

In [42]:
sample_array = np.arange(20)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
sample_array + sample_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [44]:
sample_array*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [45]:
np.exp(sample_array)#exponential of al elements

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [46]:
np.sqrt(sample_array)#square root of all elements

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [47]:
np.log(sample_array)#log of all elements

C:\Users\suresh\AppData\Local\Temp\ipykernel_26944\3358427285.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(sample_array)#log of all elements


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
#max, min and there arguement one is known

In [ ]:
np.var(sample_array)#will give variance
np.mean(sample_array)#will give mean
np.round(sample_array)#will round it of

In [48]:
sp = np.array(['soccer','cricket','soccer','squash','tennis'])
np.unique(sp)#will omit any repetition of elements and dtype gives length of longest string when string used

array(['cricket', 'soccer', 'squash', 'tennis'], dtype='<U7')